import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { pretendard } from "./fonts";
import HeaderContainer from "@/containers/common/HeaderContainer";
import FooterContainer from "@/containers/common/FooterContainer";

export const metadata: Metadata = {
  title: "GIVEN's LOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${pretendard.variable} antialiased relative`}>
        <Providers>
          <HeaderContainer />
          <main
            id="container"
            className="flex min-h-screen w-full flex-col items-center relative bg-white dark:bg-neutral-800 transition-colors duration-200"
          >
            <div className="w-full max-w-[1082px]">{children}</div>
          </main>
          <FooterContainer />
        </Providers>
      </body>
    </html>
  );
}
