import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { pretendard } from "./fonts";
import HeaderContainer from "@/containers/common/HeaderContainer";
import FooterContainer from "@/containers/common/FooterContainer";

export const metadata: Metadata = {
  title: "GIVEN's LOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${pretendard.variable} antialiased relative`}>
        <Providers>
          <HeaderContainer />
          <main
            id="container"
            className="py-10 flex min-h-screen w-[calc(100%-32px)] max-w-[1082px] flex-col mx-auto relative bg-white dark:bg-neutral-800 transition-colors duration-200"
          >
            {children}
          </main>
          <FooterContainer />
        </Providers>
      </body>
    </html>
  );
}
